### ISSUE TITLE
Errors on bootstrap

### ISSUE THREAD

**Issue by kasbah** [aya-experience/citation#7]
Hey, I am mainly interested in the GraphQL Git API. I couldn't run a dev server however. When I run `npm run bootstrap`: 

```
> citation@0.1.0 bootstrap ./citation
> lerna bootstrap

Lerna v2.0.0-beta.37
Bootstrapping 5 packages
Preinstalling packages
Installing external dependencies
NpmUtilities.installInDir     ("./citation-server", ["nodegit@^0.17.0"])
Command exited with status 1: npm install
Errored while running BootstrapCommand.execute
Command exited with status 1: npm install

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "~/.nvm/versions/node/v6.3.1/bin/node" "~/.nvm/versions/node/v6.3.1/bin/npm" "run" "bootstrap"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! citation@0.1.0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the citation@0.1.0 bootstrap script 'lerna bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the citation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs citation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls citation
npm ERR! There is likely additional logging output above.
```

As I am mainly interested in the citation-server I tried `cd citation-server` `npm install` and `npm run build` but I get:

```
$ npm install
...
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "~/.nvm/versions/node/v6.3.1/bin/node" "~/.nvm/versions/node/v6.3.1/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path ./node_modules/citation-react-renderer/lib/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod './node_modules/citation-react-renderer/lib/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod './node_modules/citation-react-renderer/lib/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     ./npm-debug.log
```

```
$ lib/cli.js
...
module.js:442
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (./node_modules/nodegit/dist/nodegit.js:18:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I would prefer not having to run it in Docker.

**Comment by Swiip** [comment]
Hey, I think you are our first public contact ;)

If I understand well your logs, in the first case, it misses a `npm install` to have lerna locally before using `npm run bootstrap` to basically run `npm install` on every modules. In the second logs, you can't run the server without the bootstrap as you need symlinks between each modules.

**Comment by kasbah** [comment]
I could have sworn I did that but nuking `citation-server/node_modules` and `npm install` fixed it.  It now binds to `localhost:4000` serving an empty page and the API seems to be on `localhost:4000/graphql`. Is there a Graph_i_QL client enabled? By the way, it still reports some errors:

```

> citation@0.1.0 nodemon:server .
> cd citation-demo && nodemon ./citation-server/lib/cli.js --watch ./citation-server/lib

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: ./citation-server/lib/**/*
[nodemon] starting `node ./citation-server/lib/cli.js`
info: [Server] Server running at: http://x230:4000
info: [GitUpdater] Starting...
error: [NodeGit] Check return false following error Error: ENOENT: no such file or directory, access './citation-demo/work/master'
info: [GitUpdater] Repository https://github.com/aya-experience/citation-demo-content.git not ready at ./citation-demo/work/master, cloning...
info: [GitUpdater] https://github.com/aya-experience/citation-demo-content.git clone done
info: [NodeGit] With changes : false
info: [GitUpdater] End
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
info: [GitUpdater] Starting...
info: [NodeGit] With changes : false
info: [GitUpdater] End
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'
error: [GitUpdater] Gitasdb read object error Error: ENOENT: no such file or directory, scandir './citation-demo/work/master/Page/second'

```

Re: first public contact, I found your project by searching for `git` and `graphql` on npm. :)

**Comment by Swiip** [comment]
Cool! At this point, you are where we are in development, Citation is currently under heavy dev.

I didn't plug a Graphiql client but it should be possible, I imagine.

**Comment by kasbah** [comment]
Cool, I'll have a dig around, thanks very much for your help!
